"""Initial migration - create all tables

Revision ID: 001
Revises: 
Create Date: 2026-02-12 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types
    dasha_planet_enum = sa.Enum('sun', 'moon', 'mars', 'mercury', 'jupiter', 'venus', 'saturn', 'rahu', 'ketu', name='dasha_planet')
    dasha_planet_enum.create(op.get_bind())
    
    generation_status_enum = sa.Enum('pending', 'processing', 'completed', 'failed', 'fallback_used', name='generation_status')
    generation_status_enum.create(op.get_bind())
    
    # Sessions table
    op.create_table(
        'sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'])
    
    # Worlds table
    op.create_table(
        'worlds',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('job_id', sa.String(length=255), nullable=False),
        sa.Column('dasha_planet', sa.Enum('sun', 'moon', 'mars', 'mercury', 'jupiter', 'venus', 'saturn', 'rahu', 'ketu', name='dasha_planet'), nullable=False),
        sa.Column('archetype', sa.String(length=100), nullable=False),
        sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'fallback_used', name='generation_status'), nullable=False),
        sa.Column('progress_percent', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('splat_url', sa.String(length=512), nullable=True),
        sa.Column('glb_url', sa.String(length=512), nullable=True),
        sa.Column('collision_mesh_url', sa.String(length=512), nullable=True),
        sa.Column('biome_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.Column('api_calls_made', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('generation_duration_seconds', sa.Float(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_worlds_job_id', 'worlds', ['job_id'])
    
    # Readings table
    op.create_table(
        'readings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('reading_type', sa.String(length=50), nullable=False),
        sa.Column('coherence_score', sa.Float(), nullable=True),
        sa.Column('lqd_score', sa.Float(), nullable=True),
        sa.Column('entropy_score', sa.Float(), nullable=True),
        sa.Column('breath_phase', sa.String(length=20), nullable=True),
        sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Artifacts table
    op.create_table(
        'artifacts',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('world_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('reading_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('artifact_type', sa.String(length=50), nullable=False),
        sa.Column('element', sa.String(length=20), nullable=True),
        sa.Column('position_x', sa.Float(), nullable=True),
        sa.Column('position_y', sa.Float(), nullable=True),
        sa.Column('position_z', sa.Float(), nullable=True),
        sa.Column('rotation', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('scale', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('state', sa.String(length=20), nullable=False, server_default='dormant'),
        sa.Column('discovered_at', sa.DateTime(), nullable=False),
        sa.Column('integrated_at', sa.DateTime(), nullable=True),
        sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['reading_id'], ['readings.id'], ),
        sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # API Usage table
    op.create_table(
        'api_usage',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('endpoint', sa.String(length=255), nullable=False),
        sa.Column('request_type', sa.String(length=50), nullable=False),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_user_id', 'api_usage', ['user_id'])
    
    # Rate Limits table
    op.create_table(
        'rate_limits',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('last_request_at', sa.DateTime(), nullable=False),
        sa.Column('request_count', sa.Integer(), nullable=False, server_default='1'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limits_user_id', 'rate_limits', ['user_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_index('ix_rate_limits_user_id', table_name='rate_limits')
    op.drop_table('rate_limits')
    
    op.drop_index('ix_api_usage_user_id', table_name='api_usage')
    op.drop_table('api_usage')
    
    op.drop_table('artifacts')
    op.drop_table('readings')
    
    op.drop_index('ix_worlds_job_id', table_name='worlds')
    op.drop_table('worlds')
    
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    
    # Drop enum types
    sa.Enum('pending', 'processing', 'completed', 'failed', 'fallback_used', name='generation_status').drop(op.get_bind())
    sa.Enum('sun', 'moon', 'mars', 'mercury', 'jupiter', 'venus', 'saturn', 'rahu', 'ketu', name='dasha_planet').drop(op.get_bind())
    
    # ### end Alembic commands ###
